const estadisticas = [
  {
    tech: 'HTML',
    percent: 85,
    delay: 0.5,
    key: 1,
  },
  {
    tech: 'CSS',
    percent: 85,
    delay: 0.7,
    key: 2,
  },
  {
    tech: 'JAVASCRIPT',
    percent: 80,
    delay: 0.9,
    key: 3,
  },
  {
    tech: 'REACT',
    percent: 75,
    delay: 1.1,
    key: 4,
  },
  {
    tech: 'NODE JS',
    percent: 55,
    delay: 1.3,
    key: 5,
  },
  {
    tech: 'MONGO DB',
    percent: 55,
    delay: 1.3,
    key: 6,
  },
]

const projects = [
  {
    key: 1,
    direction: 'row',
    directionBoxLeft: '35',
    directionBoxRight: 'none',
    directionTech: 'flex-start',
    directionTitle: 'start',
    icons: 'flex-start',
    tech1: 'Styled Components',
    tech2: 'React',
    tech3: 'MONGO DB',
    tech4: 'NPM',
    delay: '0.8',
    img: 'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
    ref: 'ref1',
    inView: 'inView1',
    alt: 'test',
    title: 'Test App',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic magnam dolores doloremque tempora iure velit, sit amet consectetur adipisicing elit.',
  },
  {
    key: 2,
    direction: 'row-reverse',
    directionBoxLeft: 'none',
    directionBoxRight: '35',
    directionTech: 'flex-end',
    directionTitle: 'end',
    icons: 'flex-end',
    tech1: 'Styled Components',
    tech2: 'React',
    tech3: 'MONGO DB',
    tech4: 'NPM',
    delay: '1.3',
    img: 'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
    ref: 'ref2',
    inView: 'inView2',
    alt: 'test',
    title: 'Test App',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic magnam dolores doloremque tempora iure velit, sit amet consectetur adipisicing elit.',
  },
  {
    key: 3,
    direction: 'row',
    directionBoxLeft: '35',
    directionBoxRight: 'none',
    directionTech: 'flex-start',
    directionTitle: 'start',
    icons: 'flex-start',
    tech1: 'Styled Components',
    tech2: 'React',
    tech3: 'MONGO DB',
    tech4: 'NPM',
    delay: '1.8',
    img: 'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
    ref: 'ref3',
    inView: 'inView3',
    alt: 'test',
    title: 'Test App',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic magnam dolores doloremque tempora iure velit, sit amet consectetur adipisicing elit.',
  },
]

const data = { estadisticas, projects }

export default data
